# Generated by Django 6.0.1 on 2026-02-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated required skills')),
                ('nice_to_have_skills', models.TextField(blank=True, help_text='Comma-separated nice-to-have skills')),
                ('required_experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5-10 years)'), ('lead', 'Lead / Principal (10+ years)')], default='entry', max_length=20)),
                ('min_years_experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(default='Remote', max_length=200)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], default='candidate', max_length=20)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills (e.g. Python, Django, SQL)')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5-10 years)'), ('lead', 'Lead / Principal (10+ years)')], max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20)),
                ('points_total', models.IntegerField(default=0)),
                ('points_breakdown', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-points_total'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
