# Generated by Django 6.0.1 on 2026-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], max_length=20, null=True),
        ),
    ]
